# Generated by Django 5.0.6 on 2026-05-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('CREDITO', 'Cartão de Crédito'), ('DEBITO', 'Cartão de Débito'), ('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro')], default='DINHEIRO', max_length=20),
        ),
    ]
