# Generated by Django 5.0.6 on 2026-06-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_produto_estoque_minimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_loja', models.CharField(default='AimSync SGC', max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('mensagem_rodape', models.TextField(blank=True, default='Obrigado pela preferência!', null=True)),
                ('imposto_padrao', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentagem de imposto padrão', max_digits=5)),
            ],
        ),
    ]
