# Generated by Django 5.0.6 on 2026-06-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_configuracaoloja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('DONO', 'Dono da Loja'), ('FUNCIONARIO', 'Funcionário')], default='FUNCIONARIO', max_length=50),
        ),
    ]
